from __future__ import annotations
import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / 'scripts/generate-dg-figures.py'
MASTER_DIR = ROOT / 'assets/math-art'
NAMES = [
    'F08-curves-frenet-frames-v4.svg',
    'F09-parameterized-surface-metric-v4.svg',
    'F10-gaussian-curvature-field-v4.svg',
    'F11-computed-geodesics-v4.svg',
    'F12-tangent-vector-field-v4.svg',
    'F13-laplace-beltrami-heat-flow-v4.svg',
]

failures=[]
with tempfile.TemporaryDirectory() as td:
    out=Path(td)
    subprocess.run([sys.executable, str(GEN), '--out-dir', str(out)], check=True)
    for name in NAMES:
        expected=MASTER_DIR/name
        generated=out/name
        if not expected.exists():
            failures.append(f'{name}: committed master missing')
            continue
        if not generated.exists():
            failures.append(f'{name}: generator output missing')
            continue
        a=expected.read_bytes(); b=generated.read_bytes()
        sha=hashlib.sha256(a).hexdigest()
        if a != b:
            failures.append(f'{name}: regenerated bytes differ from committed master')
        else:
            print(f'PASS {name}: deterministic sha256={sha}')

print(f'DG deterministic regression: {len(NAMES)-len(failures)} passes, {len(failures)} failures')
for item in failures:
    print('FAIL',item,file=sys.stderr)
if failures:
    raise SystemExit(1)
